2022-03-20 21:04:35,700:ERROR:assert_statement:assert_statement.py:Can not divide by zero - 
Traceback (most recent call last):
  File "/Users/vpb/Documents/01_ds/git/00_data_science_general_concepts/30_unittesting/assert_statement.py", line 16, in divide
    assert y != 0
AssertionError
2022-03-20 21:05:06,058:ERROR:assert_statement:assert_statement.py:Can not divide by zero - 
Traceback (most recent call last):
  File "/Users/vpb/Documents/01_ds/git/00_data_science_general_concepts/30_unittesting/assert_statement.py", line 16, in divide
    assert y != 0
AssertionError
2022-03-20 21:05:17,105:ERROR:assert_statement:assert_statement.py:Can not divide by zero - 
Traceback (most recent call last):
  File "/Users/vpb/Documents/01_ds/git/00_data_science_general_concepts/30_unittesting/assert_statement.py", line 16, in divide
    assert y != 0
AssertionError
